### ISSUE TITLE
Imprecise Results in Analyzed Model - BarElement coordinate transformation

### ISSUE THREAD

**Issue by MLiranzo** [BriefFiniteElementNet/BriefFiniteElement.Net#161] opened 2023-09-07 06:10 UTC
hello epsi1on
I have been analyzing the model shown below and observing the result of the bending moments in the column elements, I realize that the moments with respect to the local "y" axis for seismic forces in the X-X direction is similar to the moments with respect to the local "y" axis. local "z" for the same forces. This does not seem reasonable to me because if the state of seismic load in the X-X direction does not have components of the Y-Y direction, which is my case, there should be no moment with respect to the perpendicular axis.

public class Program
    {
        public static void Main(string[] args)
        {
            var h = 0.3;//200mm
            var w = 0.3;//100mm
            var h1 = 0.4;//200mm
            var w1 = 0.25;//100mm

            var e = 2.189e9;
            var m = 1000.0;
            var n = 800.0;

            Node node1, node2, node3, node4, node5, node6, node7, node8;
            BarElement element1, element2, element3, element4, element5, element6, element7, element8;
            Model model;
            string dl = "", lqx = "", lqy = "";
            LoadCase lc_dl;
            LoadCase lc_eqx;
            LoadCase lc_eqy;

            {
                var geo = SectionGenerator.GetRectangularSection(h, w);
                var geo1 = SectionGenerator.GetRectangularSection(h1, w1);

                var sec = new UniformGeometric1DSection(geo);
                var sec1 = new UniformGeometric1DSection(geo1);

                var mat = new UniformIsotropicMaterial(e, 0.3);

                node1 = new BriefFiniteElementNet.Node(0, 0, 0) { Label = "n1" };
                node2 = new BriefFiniteElementNet.Node(3.5, 0, 0) { Label = "n2" };
                node3 = new BriefFiniteElementNet.Node(0, 0, 2.62) { Label = "n3" };
                node4 = new BriefFiniteElementNet.Node(3.5, 0, 2.62) { Label = "n4" };

                node5 = new BriefFiniteElementNet.Node(0, 3, 0) { Label = "n5" };
                node6 = new BriefFiniteElementNet.Node(3.5, 3, 0) { Label = "n6" };
                node7 = new BriefFiniteElementNet.Node(0, 3, 2.62) { Label = "n7" };
                node8 = new BriefFiniteElementNet.Node(3.5, 3, 2.62) { Label = "n8" };

                node1.Constraints = Constraints.Fixed;
                node2.Constraints = Constraints.Fixed;
                node5.Constraints = Constraints.Fixed;
                node6.Constraints = Constraints.Fixed;

                element1 = new BarElement(node3, node4) { Section = sec1, Material = mat, };
                element2 = new BarElement(node1, node3) { Section = sec, Material = mat, }; // col1
                element3 = new BarElement(node2, node4) { Section = sec, Material = mat, }; // col2

                element4 = new BarElement(node7, node8) { Section = sec1, Material = mat, };
                element5 = new BarElement(node5, node7) { Section = sec, Material = mat, }; // col3
                element6 = new BarElement(node6, node8) { Section = sec, Material = mat, }; // col4

                element7 = new BarElement(node3, node7) { Section = sec1, Material = mat, };
                element8 = new BarElement(node4, node8) { Section = sec1, Material = mat, };

                lc_dl = new LoadCase(dl, LoadType.Dead);
                lc_eqx = new LoadCase(lqx, LoadType.Quake);
                lc_eqy = new LoadCase(lqy, LoadType.Quake);

                element1.Loads.Add(new UniformLoad(lc_dl, -Vector.K, m, CoordinationSystem.Global));
                element4.Loads.Add(new UniformLoad(lc_dl, -Vector.K, m, CoordinationSystem.Global));
                element7.Loads.Add(new UniformLoad(lc_dl, -Vector.K, n, CoordinationSystem.Global));
                element8.Loads.Add(new UniformLoad(lc_dl, -Vector.K, n, CoordinationSystem.Global));

                var fuerzax = new Force(m * Vector.I, Vector.Zero);
                var fuerzay = new Force(m * Vector.J, Vector.Zero);

                node3.Loads.Add(new NodalLoad(fuerzax, lc_eqx));
                node7.Loads.Add(new NodalLoad(fuerzax, lc_eqx));

                node3.Loads.Add(new NodalLoad(fuerzay, lc_eqy));
                node4.Loads.Add(new NodalLoad(fuerzay, lc_eqy));

                model = new Model();

                model.Nodes.Add(node1, node2, node3, node4, node5, node6, node7, node8);
                model.Elements.Add(element1, element2, element3, element4, element5, element6, element7, element8);

                var elp = new RigidElement(node3, node4, node7, node8);
                elp.AppliedLoadCases.Add(lc_eqx); // Sismic LoadCase in X
                elp.AppliedLoadCases.Add(lc_eqy); // Sismic LoadCase in y
                elp.AppliedLoadTypes.Add(LoadType.Quake);

                model.RigidElements.Add(elp);

                model.Solve_MPC();
            }
            
            var lstElem = new List<BarElement>() { element2, element3, element5, element6 }; // Column elements

            foreach (BarElement elem in lstElem)
            {
                var f1 = elem.GetExactInternalForceAt(-0.99999999999, lc_eqx);  
                var f9 = elem.GetExactInternalForceAt(0.999999999999, lc_eqx);

                Math.Round(f1.My, 3);
                Math.Round(f9.My, 3);

                Math.Round(f1.Mz, 3);
                Math.Round(f9.Mz, 3);

                Console.WriteLine("My 1 = " + Math.Round(f1.My, 3) + " : " + "Mz 1 = " + Math.Round(f1.Mz, 3));
                Console.WriteLine("My 2 = " + Math.Round(f9.My, 3) + " : " + "Mz 2 = " + Math.Round(f9.Mz, 3));
            }
        }
    }

Results
My 1 = 656.6 : Mz 1 = 657.176
My 2 = -653.4 : Mz 2 = -652.824
My 1 = 656.6 : Mz 1 = 657.176
My 2 = -653.4 : Mz 2 = -652.824
My 1 = 656.6 : Mz 1 = 657.176
My 2 = -653.4 : Mz 2 = -652.824
My 1 = 656.6 : Mz 1 = 657.176
My 2 = -653.4 : Mz 2 = -652.824

**Comment by epsi1on** [comment] 2023-09-07 14:35
hello,
I think result from `GetExactInternalForceAt()` needs to be converted from local coordinate to global coordinate. can you do that too?

Thanks

**Comment by MLiranzo** [comment] 2023-09-07 15:08
Thanks for you attention,
Is there any method for do it?

**Comment by epsi1on** [comment] 2023-09-08 06:27
something like this should work
```
var mgr = bar.GetTransformationManager();
var buf = mgr.TransformLocalToGlobal(local);
```

**Comment by MLiranzo** [comment] 2023-09-08 18:47
Thanks very kind.

**Comment by epsi1on** [comment] 2023-09-08 19:08
If it is resolved, then can you please close the issue?
Thanks

**Comment by MLiranzo** [comment] 2023-09-09 01:58
Hello epsi1on,
The logic doesn't seem to be working properly for me. I explain my point, when I apply horizontal loads in a seismic load case at X-X the resulting moments in the columns will be congruent with the direction of the applied loads. When I apply the methods
var mgr = bar.GetTransformationManager();
var buf = mgr.TransformLocalToGlobal(local);
Results are always reported with respect to the same axis no matter what load case you use.

[Example C-161.txt](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/12564391/Example.C-161.txt)

            }

**Comment by epsi1on** [comment] 2023-09-09 07:47
Good,
Is it possible to reduce the size of model into 1 element and 2 node, which reproduces the bug? it is a little big model, which makes it hard to understand what is going on. Also i see you are using rigid element, if you remove the rigid element, will it work good?

Regards

**Comment by MLiranzo** [comment] 2023-09-11 16:31
Thanks,
[Example C-161_2.txt](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/12578469/Example.C-161_2.txt)

**Comment by epsi1on** [comment] 2023-09-12 06:15
Here is the output for the code:

```
My 1 = 3500 : Mz 1 = 0
My 2 = 0 : Mz 2 = 0
```
It makes sense, because while you are using a vertical element, Mz will be torsion moment which is zero. instead `Mx` and `My` are nonzero. eqx will cause My, and eqy will cause Mx. this is what you probably mean:

```
Console.WriteLine("Mx 1 = " + Math.Round(buf.Mx, 3) + " : " + "My 1 = " + Math.Round(buf2.My, 3));
Console.WriteLine("Mx 2 = " + Math.Round(buf1.Mx, 3) + " : " + "My 2 = " + Math.Round(buf3.My, 3));
```

**Comment by MLiranzo** [comment] 2023-09-12 15:05
Hello epsi1on,
Thanks for the quick response, logic tells me that if I have lateral force in the global "x" direction, a bending moment will occur in the local "z" axis, in the same way if I have forces in the global "Y" axis, a bending moment will occur. on the local "y" axis. Maybe I could have a confusion in the interpretation of the local axes system. Namely, in columns the local x' axis coincides with the address of the element, the local y' axis is parallel to the global X axis, the local z' axis is parallel to the global Y axis.
![DIAGEJES](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/assets/53960987/16d382d6-dea7-45f2-9aef-6c74aca0d82c)

**Comment by epsi1on** [comment] 2023-09-12 16:23
I think the way that bfe convert local and global axis is different. (look at incomplete doc[ here](mgr.TransformLocalToGlobal)).
actually the axis you labeled `z'` is local `y` in BFE, and your `y'` is `-z'` of bfe. Also note that you converted the local forces into global forces in your code:

```
var mgr = element1.GetTransformationManager();

var buf = mgr.TransformLocalToGlobal(f1);
var buf1 = mgr.TransformLocalToGlobal(f9);

var buf2 = mgr.TransformLocalToGlobal(f1a);
var buf3 = mgr.TransformLocalToGlobal(f9a);
```

so the result is in global coordinate system, if you want local ones, then use `f1,f9,f1a,f9a` instead of `buf,buf1,etc.`

**Comment by MLiranzo** [comment] 2023-09-12 20:25
Thank you,
Apparently I have a conflict with the local axes of columns, I understand the steps indicated to manage the axes in beam elements, however, I am not very clear with the local axes in column elements.

**Comment by epsi1on** [comment] 2023-09-13 05:09
> Thank you, Apparently I have a conflict with the local axes of columns, I understand the steps indicated to manage the axes in beam elements, however, I am not very clear with the local axes in column elements.

You are right, vertical BarElement s are specific case, here is the code for calculating transformation matrix of bar element:
https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/blob/e46bf72ca4c49f592b2762487ff1169704658164/Sources/BriefFiniteElementNet/Utils/CalcUtil.cs#L899
As you can see in line 920:
https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/blob/e46bf72ca4c49f592b2762487ff1169704658164/Sources/BriefFiniteElementNet/Utils/CalcUtil.cs#L920C69-L920C69

If element is vertical, (i.e. DeltaX = DeltaY = 0), and `Node2.Z` > `Node1.Z`, then

- Global Z equals to Local X
- Global Y equals to Local Y
- Global X equals to negative Local X

in code (line 922):

```
if (v.Z > 0)
{
  czx = 1;
  cyy = 1;
  cxz = -1;
}
```

**Comment by epsi1on** [comment] 2023-09-13 05:22
Also note that coordination transformation conversion follows the logic described in this book:

Finite Element Analysis: Theory and Programming by by C Krishnamoorthy  (page 243), you can refer to that book for more information:

> The global axes are brought to coinside with the local member axes by seauence of rotation about y, z and x axes respectively. This is refered to an y-z-x transformation

**Comment by epsi1on** [comment] 2023-09-13 13:52
code for transforming local to global is in https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/blob/e46bf72ca4c49f592b2762487ff1169704658164/Sources/BriefFiniteElementNet/Utils/CalcUtil.cs#L899

code is ported from MATLAB code. from book ‘MATLAB Codes for Finite Element Analysis’ by ‘A. J. M. Ferreira’ , section 8.3 (First 3D frame example) page 107 (111 of 236)
```
    if x1 == x2 & y1 == y2
        if z2 > z1
            Lambda = [0 0 1 ; 0 1 0 ; -1 0 0];
        else
            Lambda = [0 0 -1 ; 0 1 0 ; 1 0 0];
        end
    else
        CXx = (x2-x1)/L;
        CYx = (y2-y1)/L;
        CZx = (z2-z1)/L;
        D = sqrt(CXx*CXx + CYx*CYx);
        CXy = -CYx/D;
        CYy = CXx/D;
        CZy = 0;
        CXz = -CXx*CZx/D;
        CYz = -CYx*CZx/D;
        CZz = D;
        Lambda = [CXx CYx CZx ;CXy CYy CZy ;CXz CYz CZz];

```

**Comment by MLiranzo** [comment] 2023-09-13 15:04
Thanks for the explanations, now I am more edified.

**Comment by epsi1on** [comment] 2023-09-25 06:39
inactivity

**Closed by epsi1on** 2023-09-25 06:39 UTC
