### ISSUE TITLE
Initial nodal displacement

### ISSUE THREAD

**Issue by darrenmjones** [BriefFiniteElementNet/BriefFiniteElement.Net#41] opened 2020-05-17 13:37 UTC
Hi,
Thanks very much for making this library publically available.

I would like to apply initial settlements to nodes as the feature list includes "Considering initial displacements (settlements)".

However when I include the code 

```
model.Nodes[10].Settlements = new Displacement(0, 0, 0, 0, 0, 0);
```

I am being told that Node.Settlements is read-only.

Can you advise how I should apply initial nodal settlements ?

Thanks very much,
Darren.

**Comment by epsi1on** [comment] 2020-05-17 14:50
Hello,
use `model.Nodes[10].Settlements.Add(new Settlement(0.001))` to add a 1mm (0.001m) settlement

**Comment by darrenmjones** [comment] 2020-05-17 16:35
Thanks for the quick response !

I should clarify my question - I have fixed Node 10 (the central support for a 2 span beam) in the Z direction, and want to look at the effects of a 10mm settlement in Z direction here.

Your solution gives the error: "... cannot convert from double to BriefFiniteElementNet.Displacement".

So I tried:
`model.Nodes[10].Settlements.Add(new Settlement(LoadCase.DefaultLoadCase, new Displacement(0, 0, -0.010, 0, 0, 0)));`
but that gives me:

```
Node 10 displacement in Z direction is -5667910436.660 m
Node 10 rotation in YY direction is 566791043.665 rads
```

Where I was expecting a Z displacement of -0.010m.

**Comment by epsi1on** [comment] 2020-05-17 17:08
`GetSupportReaction()` gives the forces, not the displacements. I think you are getting `-5667910436.660 N` and `566791043.665 N.m` as support reactions.

**Comment by darrenmjones** [comment] 2020-05-17 17:29
No, I'm definitely getting the displacements at Node 10:

```
            var disp = nodeList[10].GetNodalDisplacement();
            Console.WriteLine("Node 10 displacement in Z direction is {0:0.000} m", disp.DZ);
            Console.WriteLine("Node 10 rotation in YY direction is {0:0.000} rads\n", disp.RY);
```
I've attached the test subroutine so you can see the full code.  Removing the settlement gives 0 displacement as expected.
[test1.zip](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/4640680/test1.zip)



Thanks for your help,
Darren.

**Comment by epsi1on** [comment] 2020-05-19 10:23
Thanks for reporting this nasty bug. I'm working on it.

**Comment by epsi1on** [comment] 2020-05-22 01:53
Temporarily solved by setting the Ordering into Natural in ln#45

it is about handling permutation in `CsparsenetQrDisplacementPermutationCalculator.cs` file.

`var order = ColumnOrdering.Natural;`

Can you please do a check again?
Thanks

**Comment by darrenmjones** [comment] 2020-05-22 19:09
Hi,
I downloaded your latest code, but can't get my projects to run anymore.  Most of the errors seem to be with missing CSparse eg.

`Error	CS0246	The type or namespace name 'CSparse' could not be found (are you missing a using directive or an assembly reference?)	BriefFiniteElementNet.Common	G:\GitHub\BriefFiniteElement.Net\BriefFiniteElementNet.Common\Extensions.cs	7	Active`

I didn't make any changes to my code.  I did try removing the CSparse projects from my solution, and re-adding them and then re-adding the references but it doesn't fix it.  I also tried adding the reference to CSparse in BriefFiniteElementNet.Common but it still gives the errors.

Darren.

**Comment by darrenmjones** [comment] 2020-05-22 19:12
Hi,

I downloaded your latest code, but can't get my projects to run anymore. Most of the errors seem to be with missing CSparse eg.

`
Error CS0246 The type or namespace name 'CSparse' could not be found (are you missing a using directive or an assembly reference?) BriefFiniteElementNet.Common G:\GitHub\BriefFiniteElement.Net\BriefFiniteElementNet.Common\Extensions.cs 7 Active`

I didn't make any changes to my code. I did try removing the CSparse projects from my solution, and re-adding them and then re-adding the references but it doesn't fix it. I also tried adding the reference to CSparse in BriefFiniteElementNet.Common but it still gives the errors.

Darren.

**Comment by epsi1on** [comment] 2020-05-23 07:27
i think you should add nuget reference to csparse.net .

**Comment by darrenmjones** [comment] 2020-05-23 11:08
Thank you, Nuget fixed it.  It's strange as I didn't need it for the first runs.

Anyway I've compared the results to what they should be and they are not correct.  Attached is a PDF showing what I expect, for a 6 kN/m line load and 10mm settlements at middle and RH supports.  I also did plots for a slightly different model which has an encastre support at the LH of the beam.

[2x20m span results.pdf](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/4671645/2x20m.span.results.pdf)

**Comment by epsi1on** [comment] 2020-05-23 12:24
There are two types of internal force: `GetInternalForce()` and `GetExactInternalForce()`
Which one do you use and see incorrect results?
Can you please send a comparison between correct and incorrect result for a single model?

Thanks

**Comment by darrenmjones** [comment] 2020-05-23 14:19
`GetInternalForce()` and `GetExactInternalForce()` give the same results.

For a 10mm centre settlement at Node 10 the BM at all elements are correct, except the two either side of Node 10.  Similar happens when I try a settlement at Node 20.  Code attached for Node 10 settlement with a comparison against what it should give.  Also the reported displacement at Node 10 does not take the settlement into accout, it reports 0.000.

[BFE-Net Node 10 settlement test.txt](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/4671908/BFE-Net.Node.10.settlement.test.txt)

[BFE-Net Node 10 settlement result.txt](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/4671899/BFE-Net.Node.10.settlement.result.txt)

**Comment by epsi1on** [comment] 2020-05-24 04:21
Can you please visualize data like the issue #24 ?

**Comment by darrenmjones** [comment] 2020-05-24 12:13
There's not much point in trying to plot too scale as BFE is giving values 200x the expected.  Have a look at the attached plot.  The forces in the elements connected to the node with settlement are incorrect.

![Test 1 Support 2 Displacement BMD #2](https://user-images.githubusercontent.com/6731572/82753788-4bd8c300-9dc0-11ea-9deb-d66110c0bbd4.png)

**Comment by darrenmjones** [comment] 2020-05-24 21:22
I have tried to work around the bug by using vertical elements at supports, and applying restraints (and settlements) to the nodes at the bottom of these.  It works, but one thing I have noticed is that the correct results are only given if the settlements are applied as LoadCase.DefaultLoadCase.  If settlements are assigned to a new loadcase all BM results for that loadcase will be 0.

See attached file.  Correct BM's are only given when loadCase 1 = LoadCase.DefaultLoadCase (line 8).

Do you know why this is ?  I have many loadcases to apply and cannot work around this.

[test 3.txt](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/4674428/test.3.txt)

**Comment by darrenmjones** [comment] 2020-05-25 12:04
I have also noticed that reactions at supports with applied settlements are incorrect.  The total of all reactions should sum to 0, but do not.  The reaction at any node should be compatible with the sum of the SF of the beam either side.

See attached which demonstrated this.

[test 4.txt](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/4677084/test.4.txt)

**Comment by epsi1on** [comment] 2020-05-26 18:30
seems there is a problem in calculating row number of rightSide in line190 to 232 of CsparsenetQrDisplacementPermutationCalculator.cs

**Comment by darrenmjones** [comment] 2020-05-28 22:10
Hi,

Did you manage to find out why settlements only work for LoadCase.DefaultLoadCase ?

I can work around the other problems, but I need to apply a few loadcases with settlements and the only way I can think of doing this at the moment is to create a new model for each loadcase.

Thanks.

**Comment by epsi1on** [comment] 2020-05-29 05:47
The problem is that model should be solved for each loadcase internally, but `model.Solve_MPC()` only solves model for default load case and when you call `node.GetNodalDisplacement(loadcase1)` it looks and see that model not solved yet for `loadcase1` then solves the model for `loadcase1` but with `model.Solver()` method which does not takes the settlements into account. I've added an overload for `Solve_MPC()` which accepts the `LoadCase` as input:

`public void Solve_MPC(params LoadCase[] cases)`

you should call it like

`model.Solve_MPC( loadcase1);`

**Comment by darrenmjones** [comment] 2020-05-30 12:14
Thank you.

I think there's something wrong with this implementation, however.  I have 2 loadcases with vertical loads and then 2 with settlements.  None of them use `LoadCase.DefaultLoadCase;`

```
LoadCase loadCase1 = new LoadCase("L1", LoadType.Dead);   // Girder
LoadCase loadCase2 = new LoadCase("L2", LoadType.Dead);   // Additional UDL 
LoadCase loadCase3 = new LoadCase("L3", LoadType.Other);  // Settlement #1  Only works with LoadCase.DefaultLoadCase; !
LoadCase loadCase4 = new LoadCase("L4", LoadType.Other);  // Settlement #2
```

I put the loadcases into an array and solve with:

```
foreach (LoadCase loadCase in loadCases)
{
    model.Solve_MPC(loadCase);
}
```

`loadCase3` does not return any results, `loadCase4` does.  When I assign `LoadCase.DefaultLoadCase;` to `loadCase3` it does return results, as does `loadCase4`.

**Comment by epsi1on** [comment] 2020-05-30 13:09
Hi,
Can you show the code that reproduces the problem?

**Comment by darrenmjones** [comment] 2020-05-30 19:57
I've attached an example which shows the problem.

Please note that the example PDF I sent you on 23 May 2020 contained an error - the examples were for 2 x 10m spans, not the 2 x 20m spans on the title.  I have attached the correction too.

[test6.txt](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/4706336/test6.txt)
[2x10m span results.pdf](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/4706337/2x10m.span.results.pdf)

**Comment by epsi1on** [comment] 2020-05-31 05:57
Can you please recheck?

**Comment by darrenmjones** [comment] 2020-05-31 11:02
Thank you !  That has fixed it.

**Comment by epsi1on** [comment] 2020-05-31 15:25
ok, so i'll close the issue

**Closed by epsi1on** 2020-05-31 15:25 UTC
Labels: bug
